AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  order-app

  Sample SAM Template for order-app
  
Globals:
  Function:
    Timeout: 3

Resources:

  # Lambda function
  lamblas:
    Type: AWS::Serverless::Application
    Properties:
      # Lambda function
      Location: ./serverless/functions.yaml

  gateway:
    Type: AWS::Serverless::Application
    Properties:
      # Api Gateway
      Location: ./serverless/api-gateway.yaml

  dynamodb:
    Type: AWS::Serverless::Application
    Properties:
      # Dynamodb table
      Location: ./serverless/dynamodb.yaml
  
  sqs:
    Type: AWS::Serverless::Application
    Properties:
      # SQS Queue
      Location: ./serverless/sqs.yaml

  sns:
    Type: AWS::Serverless::Application
    Properties:
      # SNS Topic
      Location: ./serverless/sns.yaml






