
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: AWS API Gateway.
Resources:
  OrderApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Dev
      Cors:
        AllowMethods: "'POST, GET, UPDATE, DELETE'"
        AllowHeaders: "'X-Forwarded-For'"
        AllowOrigin: "'*'"
        MaxAge: "'600'"
      Auth:
        DefaultAuthorizer: MyCognitoAuthorizer
        Authorizers:
          MyCognitoAuthorizer:
            UserPoolArn:  
              Fn::ImportValue: !Sub CognitoUserPoolArnExport
      DefinitionBody:
        'Fn::Transform':
          Name: 'AWS::Include'
          Parameters:
            Location: './api.yaml'

  ApiGwExecutionRole: 
    Type: "AWS::IAM::Role"
    Properties: 
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "apigateway.amazonaws.com"
                - "lambda.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Path: "/"

  ApiGwExecutionPolicy: 
    Type: "AWS::IAM::Policy"
    Properties: 
      PolicyName: "apigw-execution-policy"
      PolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          Action:
            - sqs:SendMessage
            - lambda:*
          Effect: Allow
          Resource:
            - Fn::ImportValue: !Sub GetOrdersArnExportNew
            # - Fn::ImportValue: !Sub PostOrdersExportArnExportNew
            - Fn::ImportValue: !Sub GetSingleOrderArnExportNew
            - Fn::ImportValue: !Sub UpdateOrderAnrExportNew
            - Fn::ImportValue: !Sub DeleteOrderArnExportNew
            - Fn::ImportValue: !Sub OrderQueueArnExport

      Roles: 
        - Ref: "ApiGwExecutionRole"

Outputs:

  OrderApiEndpoint:
    Description: "API Gateway endpoint URL for Dev stage for Order Get function"
    Value: !Sub "https://${OrderApi}.execute-api.${AWS::Region}.amazonaws.com/Dev/orders/"
    Export:
      Name: "OrderApiEndpointExport"