Resources:
  OrderCognitoPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: orders-pool
      Policies:
        PasswordPolicy:
          MinimumLength: 8
      UsernameAttributes:
        - email
      Schema:
        - AttributeDataType: String
          Name: email
          Required: true

  OrderCognitoPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref OrderCognitoPool
      ClientName: order-pool-client
      ExplicitAuthFlows:
        - ALLOW_ADMIN_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      GenerateSecret: true
      SupportedIdentityProviders:
        - COGNITO

Outputs:
  CognitoClientID:
    Description: "The client ID of the Cognito user pool"
    Value: !Ref OrderCognitoPoolClient
    Export:
      Name: "CognitoClientIDExport"
    
  CognitoUserPoolID:
    Description: "ID of the Cognito userpool"
    Value: !Ref OrderCognitoPool
    Export:
      Name: "CognitoUserPoolIDExport"
    
  CognitoUserPoolArn:
    Description: "ARN of the Cognito userpool"
    Value: !GetAtt OrderCognitoPool.Arn
    Export:
      Name: "CognitoUserPoolArnExport"

